### PR TITLE
Storybook & First presentational component

### PR DESCRIPTION
**Pull request by meiamsome**

### CODE REVIEW

**Review by Fraasi — COMMENTED** [review]
There's a typo in types/video.tsx, you're declaring  
`export interface VideoType {`  
but then importing `videoType` elsewhere.
After that I get it to compile and run without error,   
But alas, when trying to add your VideoCard component to the page:
```
G:/Code/GitClones/project-trainsite-frontend/src/App.tsx
Type error: Property 'video' is missing in type '{}' but required in type 'Readonly<VideoCardProps>'.  TS2741

    21 |             Learn React
    22 |           </a>
  > 23 |           <VideoCard />
       |            ^
    24 |         </header>
    25 |       </div>
```
Maybe this needs some typescript polishing still.
Otherwise I like how you dropped sass and just import .css files 🥇 
I like the components folder structure, nice way to keep everything tidy.

For the record, I know nothing about storybook or how to use it, so if it is somehow crucial to the project, maybe mention it in the readme and add a link to an article/homepage to quickly see what it is and learn the basics.
edit: Found https://storybook.js.org/ and to use was simple as `npm run storybook`. I can see how this can be useful.

**Comment by meiamsome** [comment]
Hey @Fraasi,
sorry for not really actually commenting on why I tagged you in here or why StoryBook or anything - I've been busy for the past week. Thanks for the `VideoType` capitalization catch, I've never used TypeScript before so guessed some of it and had to fix it after I added a linter (Capitalization particularly.) I'm surprised that this passes the tests I set up though, considering it's definitely wrong - are TypeScript imports case insensitive?

I'll fix it up and also twiddle with these commits a bit, I intended some of the third commit stuff to be in the first one.

Yeah, Storybook is what you linked, the idea being you can just build the presentational components without having to hook it all up together. Essentially, we can break the current site into components and build them all individually without having to build complete pages to check stuff. I'll modify the readme with some instructions and add that into this PR. You can see in the `src/components/VideoCard/index.stories.tsx` file that I just set up a 'story' that renders the `VideoCard` component by using the `exampleVideo`

The styles in the `.css` are just as a stop-gap until the way we go forward is decided. I'll open an issue for discussion on that.

Also, thanks for your stuff you looked at in https://github.com/Fraasi/trainsite-playground - I would've just pulled it in but `create-react-app` now [supports typescript natively](https://facebook.github.io/create-react-app/docs/adding-typescript) so I figured we should probably start with just that setup so it's a tiny bit less complicated there.

**Comment by Fraasi** [comment]
> are TypeScript imports case insensitive?   

 I have no idea, but I'm guesssing no. I've watched few videos some time ago about typescript, so I get the basics of it, but I've never used it so far. It's a learning experience for us all.
 > One thing to keep in mind: You don't need to use TypeScript for everything if you're not comfortable with it. We can add it where it makes sense and leave it where it would get too complicated. Let's wait for what you'll find out during testing and then make a final decision. 👍
 > \- *Nilsweb*
---
 > The styles in the .css are just as a stop-gap until the way we go forward is decided. I'll open an issue for discussion on that.

 Noooooo... I think we can survive without sass.  
 My experience on the matter & discussion start already [here](https://github.com/CodingTrain/project-trainsite/issues/6).

> create-react-app now supports typescript natively

Sweet.

 After you have twiddled with these changes, I think you should push this to master, so we get somekind of start going and some folder structure to src folder. It'll be easier then to make a new branch and start twiddling around a new component.

**Comment by meiamsome** [comment]
> > The styles in the .css are just as a stop-gap until the way we go forward is decided. I'll open an issue for discussion on that.
> 
> Noooooo... I think we can survive without sass.
> My experience on the matter & discussion start already [here](https://github.com/CodingTrain/project-trainsite/issues/6).

Just to clarify, I agree with this - I've used sass & React before, but really there's no need and you just end up in a mess with no real benefit. I was thinking either standardise our CSS naming with something like [BEM](http://getbem.com/) or we use some in-js styling like [styled-components](https://www.styled-components.com/) so that we can remove `.css` completely

**Comment by Fraasi** [comment]
I would propably be ok with styled-components and I see the benefits of it, but I don't see the need for it at the moment. How I usually do styling is: put all the global styles and variables in App.css, and then import component related styles in the component itself. Never had a problem with this.  
Is there a reason we would need to do it otherwise?    
Edit: might be of interest here, [css modules with react-scripts@2.0.0 and higher](https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet)

**Comment by meiamsome** [comment]
@Fraasi oooh, that's a very interesting link. We should probably use that haha. I'm going to merge these commits as they are for now.

**Pull request merged**
